version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "7781:7781"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "7779:7779"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  postgres_data:
